sonar.projectKey=yunomix2834_copyast
sonar.projectName=copyast
sonar.organization=yunomix280304
sonar.sources=src/app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8